### ISSUE TITLE
Feature: Header component

### ISSUE THREAD

**Issue by vmarcosp** [rescriptbr/rescript-conduit#11]
## Todo

- [ ] Sync layout with handoff
- [ ] Add navigation
- [ ] Add sign in button
- [ ] Add avatar 
- [ ] Burger Button + Menu
